
;characters
CHRIS				EQU $92
JILL				EQU $93
WESKER				EQU $94
REBECCA				EQU $95
BARRY				EQU $96

;enemies
ZOMBIE				EQU $98
YAWN				EQU $A0

;objects
OBJECTS				EQU $E0

STEP_LADDER			EQU $E0 ;screen 02
WOODEN_RACK			EQU $EC ;screen 02
GARGOYLE_STATUE		EQU $F0 ;screen 02, 04, 06, 07
DORM_CLOSET_A		EQU $EE ;screen 03

JEWEL_STATUE		EQU $E1
DINNIG_ROOM_CLOCK1	EQU $E2
DINNIG_ROOM_CLOCK2	EQU $E3
GUARDHOUSE_STATUE	EQU $E4
ESCALATOR_1			EQU $E5
BOOKCASE_1			EQU $E6 ;shelf
LITLE_STATUE		EQU $E7 ;gas room statue 1
BUST_SCULPTURE		EQU $E8 ;gas room statue 2
CRANK_STEP_LADDER	EQU $E9 ;ESCALATOR_2
DORM_CLOSET_B		EQU $EA ;BOOKCASE_2
DORM_003_CLOSET_B	EQU $EB
LITLE_STATUE_2		EQU $ED ;catacomb statue
CLOSET_DOOR			EQU $EF ;xray room shelf
WOODEN_BOX			EQU $F1
LAB_STEP_LADDER		EQU $F2
SURGERY_ROOM_BOX	EQU $F3
JEWEL_STATUE2		EQU $F4
ESCALATOR_1_2		EQU $F6
WOODEN_BOX_2		EQU $F9










