    const_def

    const DOOR_00
    const DOOR_01
    const DOOR_02
    const DOOR_03
    const DOOR_04
    const DOOR_05
    const DOOR_06
    const DOOR_07
    const DOOR_08
    const DOOR_09
    const DOOR_0A
    const DOOR_0B
    const DOOR_0C
    const DOOR_0D
    const DOOR_0E
    const DOOR_0F
    const DOOR_10
    const DOOR_11
    const DOOR_12
    const DOOR_13
    const DOOR_14
    const DOOR_15
    const DOOR_16
    const DOOR_17
    const DOOR_18
    const DOOR_19
    const DOOR_1A
    const DOOR_1B
    const DOOR_1C
    const DOOR_1D
    const DOOR_1E
    const DOOR_1F
    const DOOR_20
    const DOOR_21
    const DOOR_22
    const DOOR_23
    const DOOR_24
    const DOOR_25
    const DOOR_26
    const DOOR_27
    const DOOR_28
    const DOOR_29
    const DOOR_2A
    const DOOR_2B
    const DOOR_2C
    const DOOR_2D
    const DOOR_2E
    const DOOR_2F
    const DOOR_30
    const DOOR_31
    const DOOR_32
    const DOOR_33
    const DOOR_34
    const DOOR_35
    const DOOR_36
    const DOOR_37
    const DOOR_38
    const DOOR_39
    const DOOR_3A
    const DOOR_3B
    const DOOR_3C
    const DOOR_3D
    const DOOR_3E
    const DOOR_3F
    const DOOR_40
    const DOOR_41
    const DOOR_42
    const DOOR_43
    const DOOR_44
    const DOOR_45
    const DOOR_46
    const DOOR_47
    const DOOR_48
    const DOOR_49
    const DOOR_4A
    const DOOR_4B
    const DOOR_4C
    const DOOR_4D
    const DOOR_4E
    const DOOR_4F
    const DOOR_50
    const DOOR_51
    const DOOR_52
    const DOOR_53
    const DOOR_54
    const DOOR_55
    const DOOR_56
    const DOOR_57
    const DOOR_58
    const DOOR_59
    const DOOR_5A
    const DOOR_5B
    const DOOR_5C
    const DOOR_5D
    const DOOR_5E
    const DOOR_5F
    const DOOR_60
    const DOOR_61
    const DOOR_62
    const DOOR_63
    const DOOR_64
    const DOOR_65
    const DOOR_66
    const DOOR_67
    const DOOR_68
    const DOOR_69
    const DOOR_6A
    const DOOR_6B
    const DOOR_6C
    const DOOR_6D
    const DOOR_6E
    const DOOR_6F
    const DOOR_70
    const DOOR_71
    const DOOR_72
    const DOOR_73
    const DOOR_74
    const DOOR_75
    const DOOR_76
    const DOOR_77
    const DOOR_78
    const DOOR_79
    const DOOR_7A
    const DOOR_7B
    const DOOR_7C
    const DOOR_7D
    const DOOR_7E
    const DOOR_7F

