
SINGLE_DOOR_A			EQU $00 ; (4 panels)
SINGLE_DOOR_B			EQU $01 ; (6 panels)
SINGLE_DOOR_C			EQU $02 ; (6 diamond shape panels)

DOUBLE_DOOR_A			EQU $08
DOUBLE_DOOR_B			EQU $09
DOUBLE_DOOR_C			EQU $0A

DOOR_BROWN_PAL			EQU $00
DOOR_BLUE_PAL			EQU $01
DOOR_LIGHT_BROWN_PAL	EQU $02

; special door transitions
STAIRS_1_UPWARD	        EQU $7C
STAIRS_1_DOWNWARD	    EQU $7D
STAIRS_2_UPWARD	        EQU $7E
STAIRS_2_DOWNWARD	    EQU $7F
STAIRS_3_UPWARD	        EQU $80
STAIRS_3_DOWNWARD	    EQU $81
LADDER_1_UPWARD			EQU $82
LADDER_1_DOWNWARD		EQU $83
ROPE_UPWARD				EQU $84
ROPE_DOWNWARD			EQU $85
LADDER_2_UPWARD			EQU $86
LADDER_2_DOWNWARD		EQU $87
MANSION_ELEVATOR_1		EQU $88 ; to main lab's corridor
MANSION_ELEVATOR_2		EQU $89 ; from main lab's corridor
MANSION_ELEVATOR_3		EQU $8A ; to mansion kitchen
MANSION_ELEVATOR_4		EQU $8B ; to library corridor
HELIPORT_ELEVATOR_1		EQU $8C ; to heliport
HELIPORT_ELEVATOR_2		EQU $8D ; from heliport
HELIPORT_ELEVATOR_3		EQU $8E ; from heliport
HELIPORT_ELEVATOR_4		EQU $8F ; from heliport
