
LOAD_ROOM				EQU $00

CHRIS_EVENT_DATA		EQU $01
JILL_EVENT_DATA			EQU $02
WESKER_EVENT_DATA		EQU $03
REBECCA_EVENT_DATA		EQU $04
BARRY_EVENT_DATA		EQU $32
ZOMBIE_EVENT_DATA		EQU $33
SPRITE_9E_EVENT_DATA	EQU $34 ;tyrant?

LOAD_SPRITES			EQU $22

FADEIN_SCREEN			EQU $05
FADEOUT_SCREEN			EQU $20

EVENT_WAIT				EQU $06

SCREEN_PANNING_DOWN		EQU $1E
SCREEN_PANNING_UP		EQU $1F

CHANGE_ROOM_SCREEN		EQU $07

CHANGE_PLAYER_ANIM		EQU $08
CHANGE_NPC1_ANIM		EQU $09
CHANGE_NPC2_ANIM		EQU $0A
CHANGE_NPC3_ANIM		EQU $0B
CHANGE_NPC4_ANIM		EQU $35
CHANGE_NPC6_ANIM		EQU $38

SHOW_CHRIS_MESSAGE		EQU	$0C
SHOW_JILL_MESSAGE		EQU	$0D
SHOW_WESKER_MESSAGE		EQU	$0E
SHOW_REBECCA_MESSAGE	EQU	$0F
SHOW_BARRY_MESSAGE		EQU	$2E
SHOW_ENRICO_MESSAGE		EQU	$2D
SHOW_RICHARD_MESSAGE	EQU	$3D
SHOW_BRAD_MESSAGE		EQU	$40
SHOW_MISTERY_MESSAGE	EQU	$41
SHOW_SELF_DESTRUCT_MSG	EQU	$2F

CHANGE_PLAYER_FACING	EQU $10
CHANGE_NPC1_FACING		EQU $11
CHANGE_NPC2_FACING		EQU $12
CHANGE_NPC3_FACING		EQU $13
CHANGE_NPC4_FACING		EQU $30
CHANGE_NPC6_FACING		EQU $37

PLAY_SFX				EQU $1C

MOVE_WALK_PLAYER		EQU $14
MOVE_WALK_NPC1			EQU $15
MOVE_WALK_NPC2			EQU $16
MOVE_WALK_NPC3			EQU $17
MOVE_WALK_NPC4			EQU $23
MOVE_WALK_NPC5			EQU $24
MOVE_WALK_NPC6			EQU $25

MOVE_RUN_PLAYER			EQU $18
MOVE_RUN_NPC1			EQU $19
MOVE_RUN_NPC2			EQU $1A
MOVE_RUN_NPC3			EQU $1B
MOVE_RUN_NPC4			EQU $2C

MOVE_WALK_BACKWARD_PLAYER	EQU $26
MOVE_WALK_BACKWARD_NPC1		EQU $27
MOVE_WALK_BACKWARD_NPC2		EQU $29
MOVE_WALK_BACKWARD_NPC3		EQU $28
MOVE_WALK_BACKWARD_NPC4		EQU $2A
MOVE_WALK_BACKWARD_NPC5		EQU $2B


SHOW_DOOR_ANIMATION			EQU $21

END_EVENT					EQU $1D

RECEIVE_ITEM				EQU $3C

SHOW_BG_IMAGE				EQU $3A

RESET_ALL_CHARS_DATA		EQU $39

COPY_NPC1_DATA_TO_PLAYER 	EQU $3B

SHAKE_SCREEN				EQU $36

LOAD_ROOM_MASK				EQU $3F

TIGER_AND_JEWEL_STATUE		EQU $3E
;00: blue jewel side
;01: red jewel side
;02: disable jewel statue












