
LOAD_ROOM						EQU $00
		
CHRIS_DATA		        		EQU $01
JILL_DATA			    		EQU $02
WESKER_DATA		        		EQU $03
REBECCA_DATA		    		EQU $04
BARRY_DATA		        		EQU $32
ZOMBIE_DATA		        		EQU $33
ENEMY_9E_DATA	        		EQU $34
		
LOAD_SPRITES					EQU $22
		
FADEIN_SCREEN					EQU $05
FADEOUT_SCREEN					EQU $20
		
EVENT_WAIT						EQU $06
		
SCREEN_PANNING_DOWN				EQU $1E
SCREEN_PANNING_UP				EQU $1F
		
CHANGE_ROOM_CAMERA				EQU $07
		
PLAYER_ANIM			        	EQU $08
NPC1_ANIM			        	EQU $09
NPC2_ANIM			        	EQU $0A
NPC3_ANIM			        	EQU $0B
NPC4_ANIM			        	EQU $35
NPC6_ANIM			        	EQU $38
		
CHRIS_MESSAGE		    		EQU	$0C
JILL_MESSAGE		    		EQU	$0D
WESKER_MESSAGE		    		EQU	$0E
REBECCA_MESSAGE	        		EQU	$0F
BARRY_MESSAGE		    		EQU	$2E
ENRICO_MESSAGE		    		EQU	$2D
RICHARD_MESSAGE	        		EQU	$3D
BRAD_MESSAGE		    		EQU	$40
MISTERY_MESSAGE	        		EQU	$41
LAB_ALERT_MESSAGE	    		EQU	$2F
		
FACING_CW_DIR           		EQU %00000000 ; clockwise direction
FACING_CCW_DIR          		EQU %10000000 ; counter clockwise direction
		
PLAYER_FACING	        		EQU $10
NPC1_FACING		        		EQU $11
NPC2_FACING		        		EQU $12
NPC3_FACING		        		EQU $13
NPC4_FACING		        		EQU $30
NPC6_FACING		        		EQU $37
		
PLAY_SFX						EQU $1C
		
PLAYER_WALK		        		EQU $14
NPC1_WALK			    		EQU $15
NPC2_WALK			    		EQU $16
NPC3_WALK			    		EQU $17
NPC4_WALK			    		EQU $23
NPC5_WALK			    		EQU $24
NPC6_WALK			    		EQU $25
		
PLAYER_RUN			    		EQU $18
NPC1_RUN			    		EQU $19
NPC2_RUN			    		EQU $1A
NPC3_RUN			    		EQU $1B
NPC4_RUN			    		EQU $2C
		
PLAYER_BACKWARD_WALK			EQU $26
NPC1_BACKWARD_WALK				EQU $27
NPC2_BACKWARD_WALK				EQU $29
NPC3_BACKWARD_WALK				EQU $28
NPC4_BACKWARD_WALK				EQU $2A
NPC5_BACKWARD_WALK				EQU $2B
	
	
SHOW_DOOR_ANIMATION				EQU $21
	
END_EVENT						EQU $1D
	
RECEIVE_ITEM					EQU $3C
	
SHOW_BG_IMAGE					EQU $3A
	
RESET_ALL_ENTITIES_DATA			EQU $39
	
COPY_NPC1_DATA_TO_PLAYER 		EQU $3B
	
SHAKE_SCREEN					EQU $36

UPDATE_ROOM_BG_MASK				EQU $3F

; 0: rotate tiger statue right
; 1: rotate tiger statue left
; 2: disable dinning room 2F jewel statue
UPDATE_JEWELS_STATUES_STATE		EQU $3E


