
;player facing
FACING_NORTH		EQU $00
FACING_NORTH_WEST	EQU $04
FACING_WEST			EQU $08
FACING_SOUTH_WEST	EQU $0C
FACING_SOUTH		EQU $10
FACING_SOUTH_EAST	EQU $14
FACING_EAST			EQU $18
FACING_NORTH_EAST	EQU $1C


;camera facing
CAM_FACE_SOUTH			EQU $00
CAM_FACE_SOUTH_WEST		EQU $04
CAM_FACE_WEST			EQU $08
CAM_FACE_NORTH_WEST		EQU $0C
CAM_FACE_NORTH			EQU $10
CAM_FACE_NORTH_EAST		EQU $14
CAM_FACE_EAST			EQU $18
CAM_FACE_SOUTH_EAST		EQU $1C

