
NO_INPUT				EQU $00
A_INPUT					EQU $01
B_INPUT					EQU $02
AB_INPUT				EQU $03
SELECT_INPUT			EQU $04
A_SELECT_INPUT			EQU $05
B_SELECT_INPUT			EQU $06
AB_SELECT_INPUT			EQU $07
START_INPUT				EQU $08
A_START_INPUT			EQU $09
B_START_INPUT			EQU $0A
AB_START_INPUT			EQU $0B
START_SEL_INPUT			EQU $0C
A_START_SEL_INPUT		EQU $0D
B_START_SEL_INPUT		EQU $0E
AB_START_SEL_INPUT		EQU $0F

RIGHT_INPUT				EQU $10
LEFT_INPUT				EQU $20
LEFT_RIGHT_INPUT		EQU $30
UP_INPUT				EQU $40
UP_RIGHT_INPUT			EQU $50
UP_LEFT_INPUT			EQU $60
DOWN_INPUT				EQU $80
DOWN_RIGHT_INPUT		EQU $90
DOWN_LEFT_INPUT			EQU $A0

ALL_DIRECTION_INPUT		EQU $F0
ALL_DIRECTION_B_INPUT	EQU $F2
