
; menu constants

MENU_TOP_OPTIONS_ENABLED    EQU $00
MENU_TOP_OPTIONS_DISABLED   EQU $FF

MAP_OPTION			    	EQU $00
RADIO_OPTION				EQU $01
FILE_OPTION			    	EQU $02
EXIT_OPTION			    	EQU $03
	
ITEM_SLOT_1					EQU $04
ITEM_SLOT_2					EQU $05
ITEM_SLOT_3					EQU $06
ITEM_SLOT_4					EQU $07
ITEM_SLOT_5					EQU $08
ITEM_SLOT_6					EQU $09
ITEM_SLOT_7					EQU $0A
ITEM_SLOT_8					EQU $0B
	
; menu modes	
SUBMENUS_CURSOR				EQU $0C
	
FILE_MENU					EQU $0C
MAP_MENU					EQU $0E ; map select menu
RADIO_SELECTED				EQU $0D
MAP_DETAIL_MENU				EQU $12
	
ITEMBOX_CURSOR				EQU $80
	
USE_EQUIP_CURSOR			EQU $80
CHECK_ITEM_CURSOR			EQU $81
COMBINE_CURSOR				EQU $82
	
ITEM_DESC_MODE				EQU $84
	
COMBINE_ITEM_MODE			EQU $E0
	
COMBINE_SLOT_1				EQU $E4
COMBINE_SLOT_2				EQU $E5
COMBINE_SLOT_3				EQU $E6
COMBINE_SLOT_4				EQU $E7
COMBINE_SLOT_5				EQU $E8
COMBINE_SLOT_6				EQU $E9
COMBINE_SLOT_7				EQU $EA
COMBINE_SLOT_8				EQU $EB
	
GET_ITEM_MODE				EQU $FF
	
CHRIS_MAX_SLOTS         	EQU 6
JILL_MAX_SLOTS          	EQU 8
INVENTORY_MAX_SLOTS     	EQU 8
	
MAX_HEALTH              	EQU 32
	
; menu types	
MAIN_MEMU_MODE          	EQU $00
ITEMBOX_MEMU_MODE       	EQU $FF
	
MAX_ITEMBOX_ITEMS       	EQU 32
	
MAX_FILES_PER_BOOK      	EQU 13
