
NO_MUSIC					EQU $00
UNUSED_ORIGINAL_THEME_1		EQU $01 ; mansion ambient theme
UNUSED_ORIGINAL_THEME_2		EQU $02 ; fight or tension theme
UNUSED_ORIGINAL_THEME_3		EQU $03 ; mansion ambient theme
UNUSED_ORIGINAL_THEME_4		EQU $04 ; mansion ambient theme
DEFAULT_MAIN_THEME			EQU $05
WANDERING_ABOUT_THEME		EQU $06
UNUSED_ORIGINAL_THEME_5		EQU $07 ; scary theme
UNUSED_ORIGINAL_THEME_6		EQU $08 ; misterious theme
MOONLIGHT_SONATA_THEME		EQU $09
MOONLIGHT_SONATA_FAIL		EQU $0A
VACANT_FLAT_THEME			EQU $0B
UNUSED_ORIGINAL_THEME_7		EQU $0C ; sad theme
