; special room screens

EMBLEM_CHINMEY_SCREEN				EQU 6
MANSION_BATHROOM_TUB_SCREEN			EQU 3
KENNETH_CORPSE_SCREEN				EQU 5
PASSCODE_PANEL_SCREEN				EQU 7
NUMERIC_PANEL_SCREEN				EQU 5
FIREARMS_ROOM_DESK_SCREEN			EQU 3
CREST_PANEL_SCREEN					EQU 4
TIGER_STATUE_SCREEN					EQU 1
ARMORS_ROOM_BUTTON_SCREEN			EQU 3
BUG_COLLECTION_SCREEN				EQU 2
VISUAL_DATA_ROOM_PLATE_SCREEN 		EQU	4
WHITEBOARD_SCREEN					EQU 4
LAB_COMPUTER_SCREEN					EQU 4
XRAY_ROOM_PAINTING_SCREEN			EQU 4
XRAY_ROOM_PAINTING_DECODED_SCREEN	EQU 3

; tilemap images
FIRST_ZOMBIE_IMAGE                  EQU 1
FALLING_STATUE_IMAGE                EQU 2
