;special room screens

EMBLEM_CHINMEY_SCREEN		EQU $06
MANSION_BATHROOM_TUB		EQU $03
KENNETH_CORPSE_SCREEN		EQU $05
PASSCODE_PANEL_SCREEN		EQU $07
NUMERIC_PANEL_SCREEN		EQU $05
FIREARMS_ROOM_DESK_SCRN		EQU $03
CREST_PANEL_SCREEN			EQU $04
TIGER_STATUE_SCREEN			EQU $01
ARMORS_ROOM_BUTTON_SCRN		EQU $03
BUG_COLLECTION_SCREEN		EQU $02
VISUAL_DATA_ROOM_PLATE_SCRN EQU	$04
WHITEBOARD_SCREEN			EQU $04
LAB_COMPUTER_SCREEN			EQU $04
XRAY_ROOM_PAINTING			EQU $04
XRAY_ROOM_PAINTING_REVEALED	EQU $03
