
IDLE_ANIM			EQU $00
WALK_ANIM			EQU $01
RUN_ANIM			EQU $02
GUN_AIM_ANIM		EQU $03
SHOTGUN_AIM_ANIM	EQU $04
KNIFE_AIM_ANIM		EQU $05
GET_DAMAGED_ANIM	EQU $06
PICK_ITEM_ANIM		EQU $07

;zombie
DEAD_ANIM			EQU $02
ATTACK_ANIM			EQU $03
