itemsSpriteTable:: ;05:5B00
	dw item_00_spriteA
	dw item_01_spriteA
	dw item_02_spriteA
	dw item_03_spriteA
	dw item_04_spriteA
	dw item_05_spriteA
	dw item_06_spriteA
	dw item_07_spriteA
	dw item_08_spriteA
	dw item_09_spriteA
	dw item_0A_spriteA
	dw item_0B_spriteA
	dw item_0C_spriteA
	dw item_0D_spriteA
	dw item_0E_spriteA
	dw item_0F_spriteA
	dw item_10_spriteA
	dw item_11_spriteA
	dw item_12_spriteA
	dw item_13_spriteA
	dw item_14_spriteA
	dw item_15_spriteA
	dw item_16_spriteA
	dw item_17_spriteA
	dw item_18_spriteA
	dw item_19_spriteA
	dw item_1A_spriteA
	dw item_1B_spriteA
	dw item_1C_spriteA
	dw item_1D_spriteA
	dw item_1E_spriteA
	dw item_1F_spriteA
	dw item_20_spriteA
	dw item_21_spriteA
	dw item_22_spriteA
	dw item_23_spriteA
	dw item_24_spriteA
	dw item_25_spriteA
	dw item_26_spriteA
	dw item_27_spriteA
	dw item_28_spriteA
	dw item_29_spriteA
	dw item_2A_spriteA
	dw item_2B_spriteA
	dw item_2C_spriteA
	dw item_2D_spriteA
	dw item_2E_spriteA
	dw item_2F_spriteA
	dw item_30_spriteA
	dw item_31_spriteA
	dw item_32_spriteA
	dw item_33_spriteA
	dw item_34_spriteA
	dw item_35_spriteA
	dw item_36_spriteA
	dw item_37_spriteA
	dw item_38_spriteA
	dw item_39_spriteA
	dw item_3A_spriteA
	dw item_3B_spriteA
	dw item_3C_spriteA
	dw item_3D_spriteA
	dw item_3E_spriteA
	dw item_3F_spriteA
	dw item_40_spriteA
	dw item_41_spriteA
	dw item_42_spriteA
	dw item_43_spriteA
	dw item_44_spriteA
	dw item_45_spriteA
	dw item_46_spriteA
	dw item_47_spriteA
	dw item_48_spriteA
	dw item_49_spriteA
	dw item_4A_spriteA
	dw item_4B_spriteA
	dw item_4C_spriteA
	dw item_4D_spriteA
	dw item_4E_spriteA
	dw item_4F_spriteA
	dw item_50_spriteA
	dw item_51_spriteA
	dw item_52_spriteA
	dw item_53_spriteA
	dw item_54_spriteA
	dw item_55_spriteA
	dw item_56_spriteA
	dw item_57_spriteA
	dw item_58_spriteA
	dw item_59_spriteA
	dw item_5A_spriteA
	dw item_5B_spriteA
	dw item_5C_spriteA
	dw item_5D_spriteA
	dw item_5E_spriteA
	dw item_5F_spriteA
;5BC0
