
roomsCollidersTable: ;FD:4430
	dw room_00_colliders
	dw room_01_colliders
	dw room_02_colliders
	dw room_03_colliders
	dw room_04_colliders
	dw room_05_colliders
	dw room_06_colliders
	dw room_07_colliders
	dw room_08_colliders
	dw room_09_colliders
	dw room_0A_colliders
	dw room_0B_colliders
	dw room_0C_colliders
	dw room_0D_colliders
	dw room_0E_colliders
	dw room_0F_colliders
	dw room_10_colliders
	dw room_11_colliders
	dw room_12_colliders
	dw room_13_colliders
	dw room_14_colliders
	dw room_15_colliders
	dw room_16_colliders
	dw room_17_colliders
	dw room_18_colliders
	dw room_19_colliders
	dw room_1A_colliders
	dw room_1B_colliders
	dw room_1C_colliders
	dw room_1D_colliders
	dw room_1E_colliders
	dw room_1F_colliders
	dw room_20_colliders
	dw room_21_colliders
	dw room_22_colliders
	dw room_23_colliders
	dw room_24_colliders
	dw room_25_colliders
	dw room_26_colliders
	dw room_27_colliders
	dw room_28_colliders
	dw room_29_colliders
	dw room_2A_colliders
	dw room_2B_colliders
	dw room_2C_colliders
	dw room_2D_colliders
	dw room_2E_colliders
	dw room_2F_colliders
	dw room_30_colliders
	dw room_31_colliders
	dw room_32_colliders
	dw room_33_colliders
	dw room_34_colliders
	dw room_35_colliders
	dw room_36_colliders
	dw room_37_colliders
	dw room_38_colliders
	dw room_39_colliders
	dw room_3A_colliders
	dw room_3B_colliders
	dw room_3C_colliders
	dw room_3D_colliders
	dw room_3E_colliders
	dw room_3F_colliders
	dw room_40_colliders
	dw room_41_colliders
	dw room_42_colliders
	dw room_43_colliders
	dw room_44_colliders
	dw room_45_colliders
	dw room_46_colliders
	dw room_47_colliders
	dw room_48_colliders
	dw room_49_colliders
	dw room_4A_colliders
	dw room_4B_colliders
	dw room_4C_colliders
	dw room_4D_colliders
	dw room_4E_colliders
	dw room_4F_colliders
	dw room_50_colliders
	dw room_51_colliders
	dw room_52_colliders
	dw room_53_colliders
	dw room_54_colliders
	dw room_55_colliders
	dw room_56_colliders
	dw room_57_colliders
	dw room_58_colliders
	dw room_59_colliders
	dw room_5A_colliders
	dw room_5B_colliders
	dw room_5C_colliders
	dw room_5D_colliders
	dw room_5E_colliders
	dw room_5F_colliders
	dw room_60_colliders
	dw room_61_colliders
	dw room_62_colliders
	dw room_63_colliders
	dw room_64_colliders
	dw room_65_colliders
	dw room_66_colliders
	dw room_67_colliders
	dw room_68_colliders
	dw room_69_colliders
	dw room_6A_colliders
	dw room_6B_colliders
	dw room_6C_colliders
	dw room_6D_colliders
	dw room_6E_colliders
	dw room_6F_colliders
	dw room_70_colliders
	dw room_71_colliders
	dw room_72_colliders
	dw room_73_colliders
