
roomsActionsDatatable: ;C5:4000
	dw room00_ActionData
	dw room01_ActionData
	dw room02_ActionData
	dw room03_ActionData
	dw room04_ActionData
	dw room05_ActionData
	dw room06_ActionData
	dw room07_ActionData
	dw room08_ActionData
	dw room09_ActionData
	dw room0A_ActionData
	dw room0B_ActionData
	dw room0C_ActionData
	dw room0D_ActionData
	dw room0E_ActionData
	dw room0F_ActionData
	dw room10_ActionData
	dw room11_ActionData
	dw room12_ActionData
	dw room13_ActionData
	dw room14_ActionData
	dw room15_ActionData
	dw room16_ActionData
	dw room17_ActionData
	dw room18_ActionData
	dw room19_ActionData
	dw room1A_ActionData
	dw room1B_ActionData
	dw room1C_ActionData
	dw room1D_ActionData
	dw room1E_ActionData
	dw room1F_ActionData
	dw room20_ActionData
	dw room21_ActionData
	dw room22_ActionData
	dw room23_ActionData
	dw room24_ActionData
	dw room25_ActionData
	dw room26_ActionData
	dw room27_ActionData
	dw room28_ActionData
	dw room29_ActionData
	dw room2A_ActionData
	dw room2B_ActionData
	dw room2C_ActionData
	dw room2D_ActionData
	dw room2E_ActionData
	dw room2F_ActionData
	dw room30_ActionData
	dw room31_ActionData
	dw room32_ActionData
	dw room33_ActionData
	dw room34_ActionData
	dw room35_ActionData
	dw room36_ActionData
	dw room37_ActionData
	dw room38_ActionData
	dw room39_ActionData
	dw room3A_ActionData
	dw room3B_ActionData
	dw room3C_ActionData
	dw room3D_ActionData
	dw room3E_ActionData
	dw room3F_ActionData
	dw room40_ActionData
	dw room41_ActionData
	dw room42_ActionData
	dw room43_ActionData
	dw room44_ActionData
	dw room45_ActionData
	dw room46_ActionData
	dw room47_ActionData
	dw room48_ActionData
	dw room49_ActionData
	dw room4A_ActionData
	dw room4B_ActionData
	dw room4C_ActionData
	dw room4D_ActionData
	dw room4E_ActionData
	dw room4F_ActionData
	dw room50_ActionData
	dw room51_ActionData
	dw room52_ActionData
	dw room53_ActionData
	dw room54_ActionData
	dw room55_ActionData
	dw room56_ActionData
	dw room57_ActionData
	dw room58_ActionData
	dw room59_ActionData
	dw room5A_ActionData
	dw room5B_ActionData
	dw room5C_ActionData
	dw room5D_ActionData
	dw room5E_ActionData
	dw room5F_ActionData
	dw room60_ActionData
	dw room61_ActionData
	dw room62_ActionData
	dw room63_ActionData
	dw room64_ActionData
	dw room65_ActionData
	dw room66_ActionData
	dw room67_ActionData
	dw room68_ActionData
	dw room69_ActionData
	dw room6A_ActionData
	dw room6B_ActionData
	dw room6C_ActionData
	dw room6D_ActionData
	dw room6E_ActionData
	dw room6F_ActionData
	dw room70_ActionData
	dw room71_ActionData
	dw room72_ActionData
	dw room73_ActionData
