
RoomsBgCamerasLookupTable:: ;7:4000
	dw room00_camera_data
	dw room01_camera_data
	dw room02_camera_data
	dw room03_camera_data
	dw room04_camera_data
	dw room05_camera_data
	dw room06_camera_data
	dw room07_camera_data
	dw room08_camera_data
	dw room09_camera_data
	dw room0A_camera_data
	dw room0B_camera_data
	dw room0C_camera_data
	dw room0D_camera_data
	dw room0E_camera_data
	dw room0F_camera_data
	dw room10_camera_data
	dw room11_camera_data
	dw room12_camera_data
	dw room13_camera_data
	dw room14_camera_data
	dw room15_camera_data
	dw room16_camera_data
	dw room17_camera_data
	dw room18_camera_data
	dw room19_camera_data
	dw room1A_camera_data
	dw room1B_camera_data
	dw room1C_camera_data
	dw room1D_camera_data
	dw room1E_camera_data
	dw room1F_camera_data
	dw room20_camera_data
	dw room21_camera_data
	dw room22_camera_data
	dw room23_camera_data
	dw room24_camera_data
	dw room25_camera_data
	dw room26_camera_data
	dw room27_camera_data
	dw room28_camera_data
	dw room29_camera_data
	dw room2A_camera_data
	dw room2B_camera_data
	dw room2C_camera_data
	dw room2D_camera_data
	dw room2E_camera_data
	dw room2F_camera_data
	dw room30_camera_data
	dw room31_camera_data
	dw room32_camera_data
	dw room33_camera_data
	dw room34_camera_data
	dw room35_camera_data
	dw room36_camera_data
	dw room37_camera_data
	dw room38_camera_data
	dw room39_camera_data
	dw room3A_camera_data
	dw room3B_camera_data
	dw room3C_camera_data
	dw room3D_camera_data
	dw room3E_camera_data
	dw room3F_camera_data
	dw room40_camera_data
	dw room41_camera_data
	dw room42_camera_data
	dw room43_camera_data
	dw room44_camera_data
	dw room45_camera_data
	dw room46_camera_data
	dw room47_camera_data
	dw room48_camera_data
	dw room49_camera_data
	dw room4A_camera_data
	dw room4B_camera_data
	dw room4C_camera_data
	dw room4D_camera_data
	dw room4E_camera_data
	dw room4F_camera_data
	dw room50_camera_data
	dw room51_camera_data
	dw room52_camera_data
	dw room53_camera_data
	dw room54_camera_data
	dw room55_camera_data
	dw room56_camera_data
	dw room57_camera_data
	dw room58_camera_data
	dw room59_camera_data
	dw room5A_camera_data
	dw room5B_camera_data
	dw room5C_camera_data
	dw room5D_camera_data
	dw room5E_camera_data
	dw room5F_camera_data
	dw room60_camera_data
	dw room61_camera_data
	dw room62_camera_data
	dw room63_camera_data
	dw room64_camera_data
	dw room65_camera_data
	dw room66_camera_data
	dw room67_camera_data
	dw room68_camera_data
	dw room69_camera_data
	dw room6A_camera_data
	dw room6B_camera_data
	dw room6C_camera_data
	dw room6D_camera_data
	dw room6E_camera_data
	dw room6F_camera_data
	dw room70_camera_data
	dw room71_camera_data
	dw room72_camera_data
	dw room73_camera_data
;40E8
