
;rooms BG loopup table
;word1: screens BG lookup table pointer
;word2: BG pallete pointer

;1:71B5
	dw room_00_bg_pointers, room_00_pallete
	dw room_01_bg_pointers, room_01_pallete
	dw room_02_bg_pointers, room_02_pallete
	dw room_03_bg_pointers, room_03_pallete
	dw room_04_bg_pointers, room_04_pallete
	dw room_05_bg_pointers, room_05_pallete
	dw room_06_bg_pointers, room_06_pallete
	dw room_07_bg_pointers, room_07_pallete
	dw room_08_bg_pointers, room_08_pallete
	dw room_09_bg_pointers, room_09_pallete
	dw room_0A_bg_pointers, room_0A_pallete
	dw room_0B_bg_pointers, room_0B_pallete
	dw room_0C_bg_pointers, room_0C_pallete
	dw room_0D_bg_pointers, room_0D_pallete
	dw room_0E_bg_pointers, room_0E_pallete
	dw room_0F_bg_pointers, room_0F_pallete
	dw room_10_bg_pointers, room_10_pallete
	dw room_11_bg_pointers, room_11_pallete
	dw room_12_bg_pointers, room_12_pallete
	dw room_13_bg_pointers, room_13_pallete
	dw room_14_bg_pointers, room_14_pallete
	dw room_15_bg_pointers, room_15_pallete
	dw room_16_bg_pointers, room_16_pallete
	dw room_17_bg_pointers, room_17_pallete
	dw room_18_bg_pointers, room_18_pallete
	dw room_19_bg_pointers, room_19_pallete
	dw room_1A_bg_pointers, room_1A_pallete
	dw room_1B_bg_pointers, room_1B_pallete
	dw room_1C_bg_pointers, room_1C_pallete
	dw room_1D_bg_pointers, room_1D_pallete
	dw room_1E_bg_pointers, room_1E_pallete
	dw room_1F_bg_pointers, room_1F_pallete
	dw room_20_bg_pointers, room_20_pallete
	dw room_21_bg_pointers, room_21_pallete
	dw room_22_bg_pointers, room_22_pallete
	dw room_23_bg_pointers, room_23_pallete
	dw room_24_bg_pointers, room_24_pallete
	dw room_25_bg_pointers, room_25_pallete
	dw room_26_bg_pointers, room_26_pallete
	dw room_27_bg_pointers, room_27_pallete
	dw room_28_bg_pointers, room_28_pallete
	dw room_29_bg_pointers, room_29_pallete
	dw room_2A_bg_pointers, room_2A_pallete
	dw room_2B_bg_pointers, room_2B_pallete
	dw room_2C_bg_pointers, room_2C_pallete
	dw room_2D_bg_pointers, room_2D_pallete
	dw room_2E_bg_pointers, room_2E_pallete
	dw room_2F_bg_pointers, room_2F_pallete
	dw room_30_bg_pointers, room_30_pallete
	dw room_31_bg_pointers, room_31_pallete
	dw room_32_bg_pointers, room_32_pallete
	dw room_33_bg_pointers, room_33_pallete
	dw room_34_bg_pointers, room_34_pallete
	dw room_35_bg_pointers, room_35_pallete
	dw room_36_bg_pointers, room_36_pallete
	dw room_37_bg_pointers, room_37_pallete
	dw room_38_bg_pointers, room_38_pallete
	dw room_39_bg_pointers, room_39_pallete
	dw room_3A_bg_pointers, room_3A_pallete
	dw room_3B_bg_pointers, room_3B_pallete
	dw room_3C_bg_pointers, room_3C_pallete
	dw room_3D_bg_pointers, room_3D_pallete
	dw room_3E_bg_pointers, room_3E_pallete
	dw room_3F_bg_pointers, room_3F_pallete
	dw room_40_bg_pointers, room_40_pallete
	dw room_41_bg_pointers, room_41_pallete
	dw room_42_bg_pointers, room_42_pallete
	dw room_43_bg_pointers, room_43_pallete
	dw room_44_bg_pointers, room_44_pallete
	dw room_45_bg_pointers, room_45_pallete
	dw room_46_bg_pointers, room_46_pallete
	dw room_47_bg_pointers, room_47_pallete
	dw room_48_bg_pointers, room_48_pallete
	dw room_49_bg_pointers, room_49_pallete
	dw room_4A_bg_pointers, room_4A_pallete
	dw room_4B_bg_pointers, room_4B_pallete
	dw room_4C_bg_pointers, room_4C_pallete
	dw room_4D_bg_pointers, room_4D_pallete
	dw room_4E_bg_pointers, room_4E_pallete
	dw room_4F_bg_pointers, room_4F_pallete
	dw room_50_bg_pointers, room_50_pallete
	dw room_51_bg_pointers, room_51_pallete
	dw room_52_bg_pointers, room_52_pallete
	dw room_53_bg_pointers, room_53_pallete
	dw room_54_bg_pointers, room_54_pallete
	dw room_55_bg_pointers, room_55_pallete
	dw room_56_bg_pointers, room_56_pallete
	dw room_57_bg_pointers, room_57_pallete
	dw room_58_bg_pointers, room_58_pallete
	dw room_59_bg_pointers, room_59_pallete
	dw room_5A_bg_pointers, room_5A_pallete
	dw room_5B_bg_pointers, room_5B_pallete
	dw room_5C_bg_pointers, room_5C_pallete
	dw room_5D_bg_pointers, room_5D_pallete
	dw room_5E_bg_pointers, room_5E_pallete
	dw room_5F_bg_pointers, room_5F_pallete
	dw room_60_bg_pointers, room_60_pallete
	dw room_61_bg_pointers, room_61_pallete
	dw room_62_bg_pointers, room_62_pallete
	dw room_63_bg_pointers, room_63_pallete
	dw room_64_bg_pointers, room_64_pallete
	dw room_65_bg_pointers, room_65_pallete
	dw room_66_bg_pointers, room_66_pallete
	dw room_67_bg_pointers, room_67_pallete
	dw room_68_bg_pointers, room_68_pallete
	dw room_69_bg_pointers, room_69_pallete
	dw room_6A_bg_pointers, room_6A_pallete
	dw room_6B_bg_pointers, room_6B_pallete
	dw room_6C_bg_pointers, room_6C_pallete
	dw room_6D_bg_pointers, room_6D_pallete
	dw room_6E_bg_pointers, room_6E_pallete
	dw room_6F_bg_pointers, room_6F_pallete
	dw room_70_bg_pointers, room_70_pallete
	dw room_71_bg_pointers, room_71_pallete
	dw room_72_bg_pointers, room_72_pallete
	dw room_73_bg_pointers, room_73_pallete
;7385
