
_weskerBarrySpritesTable: ;FD:602B
;idle
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_idle_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_idle_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_idle_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_idle_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_idle_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_idle_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_idle_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_idle_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_idle_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_idle_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_idle_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_idle_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_idle_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_idle_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_idle_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_idle_anim_pointers

;walk
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_walk_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_walk_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_walk_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_walk_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_walk_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_walk_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_walk_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_walk_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_walk_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_walk_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_walk_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_walk_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_walk_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_walk_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_walk_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_walk_anim_pointers

;run (walk)
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_walk_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_walk_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_walk_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_walk_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_walk_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_walk_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_walk_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_walk_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_walk_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_walk_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_walk_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_walk_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_walk_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_walk_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_walk_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_walk_anim_pointers

;gun aim
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_gun_aim_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_gun_aim_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_gun_aim_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_gun_aim_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_gun_aim_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_gun_aim_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_gun_aim_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_gun_aim_anim_pointers

;shotgun aim
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_shotgun_aim_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_shotgun_aim_anim_pointers

;checking
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_checking_anim_pointers
	dw BANK(weskerbarry_front_spritesheet), weskerbarry_front_checking_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_checking_anim_pointers
	dw BANK(weskerbarry_front_right_spritesheet), weskerbarry_front_right_checking_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_checking_anim_pointers
	dw BANK(weskerbarry_right_spritesheet), weskerbarry_right_checking_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_checking_anim_pointers
	dw BANK(weskerbarry_back_right_spritesheet), weskerbarry_back_right_checking_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_checking_anim_pointers
	dw BANK(weskerbarry_back_spritesheet), weskerbarry_back_checking_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_checking_anim_pointers
	dw BANK(weskerbarry_back_left_spritesheet), weskerbarry_back_left_checking_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_checking_anim_pointers
	dw BANK(weskerbarry_left_spritesheet), weskerbarry_left_checking_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_checking_anim_pointers
	dw BANK(weskerbarry_front_left_spritesheet), weskerbarry_front_left_checking_anim_pointers

;61AB

weskerbarry_front_idle_anim_pointers:
	dw weskerbarry_front_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_spritesheet+IDLE_FRAME_2

weskerbarry_front_right_idle_anim_pointers:
	dw weskerbarry_front_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_right_spritesheet+IDLE_FRAME_2

weskerbarry_right_idle_anim_pointers:
	dw weskerbarry_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_right_spritesheet+IDLE_FRAME_2

weskerbarry_back_right_idle_anim_pointers:
	dw weskerbarry_back_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_right_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_right_spritesheet+IDLE_FRAME_2

weskerbarry_back_idle_anim_pointers:
	dw weskerbarry_back_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_spritesheet+IDLE_FRAME_2

weskerbarry_back_left_idle_anim_pointers:
	dw weskerbarry_back_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_back_left_spritesheet+IDLE_FRAME_2

weskerbarry_left_idle_anim_pointers:
	dw weskerbarry_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_left_spritesheet+IDLE_FRAME_2

weskerbarry_front_left_idle_anim_pointers:
	dw weskerbarry_front_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_left_spritesheet+IDLE_FRAME_1
	dw weskerbarry_front_left_spritesheet+IDLE_FRAME_2

;walk
weskerbarry_front_walk_anim_pointers:
	dw weskerbarry_front_spritesheet+WALK_FRAME_1
	dw weskerbarry_front_spritesheet+WALK_FRAME_2
	dw weskerbarry_front_spritesheet+WALK_FRAME_3
	dw weskerbarry_front_spritesheet+WALK_FRAME_4
	dw weskerbarry_front_spritesheet+WALK_FRAME_5
	dw weskerbarry_front_spritesheet+WALK_FRAME_6
	dw weskerbarry_front_spritesheet+WALK_FRAME_7
	dw weskerbarry_front_spritesheet+WALK_FRAME_8

weskerbarry_front_right_walk_anim_pointers:
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_1
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_2
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_3
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_4
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_5
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_6
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_7
	dw weskerbarry_front_right_spritesheet+WALK_FRAME_8

weskerbarry_right_walk_anim_pointers:
	dw weskerbarry_right_spritesheet+WALK_FRAME_1
	dw weskerbarry_right_spritesheet+WALK_FRAME_2
	dw weskerbarry_right_spritesheet+WALK_FRAME_3
	dw weskerbarry_right_spritesheet+WALK_FRAME_4
	dw weskerbarry_right_spritesheet+WALK_FRAME_5
	dw weskerbarry_right_spritesheet+WALK_FRAME_6
	dw weskerbarry_right_spritesheet+WALK_FRAME_7
	dw weskerbarry_right_spritesheet+WALK_FRAME_8

weskerbarry_back_right_walk_anim_pointers:
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_1
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_2
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_3
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_4
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_5
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_6
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_7
	dw weskerbarry_back_right_spritesheet+WALK_FRAME_8

weskerbarry_back_walk_anim_pointers:
	dw weskerbarry_back_spritesheet+WALK_FRAME_1
	dw weskerbarry_back_spritesheet+WALK_FRAME_2
	dw weskerbarry_back_spritesheet+WALK_FRAME_3
	dw weskerbarry_back_spritesheet+WALK_FRAME_4
	dw weskerbarry_back_spritesheet+WALK_FRAME_5
	dw weskerbarry_back_spritesheet+WALK_FRAME_6
	dw weskerbarry_back_spritesheet+WALK_FRAME_7
	dw weskerbarry_back_spritesheet+WALK_FRAME_8

weskerbarry_back_left_walk_anim_pointers:
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_1
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_2
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_3
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_4
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_5
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_6
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_7
	dw weskerbarry_back_left_spritesheet+WALK_FRAME_8

weskerbarry_left_walk_anim_pointers:
	dw weskerbarry_left_spritesheet+WALK_FRAME_1
	dw weskerbarry_left_spritesheet+WALK_FRAME_2
	dw weskerbarry_left_spritesheet+WALK_FRAME_3
	dw weskerbarry_left_spritesheet+WALK_FRAME_4
	dw weskerbarry_left_spritesheet+WALK_FRAME_5
	dw weskerbarry_left_spritesheet+WALK_FRAME_6
	dw weskerbarry_left_spritesheet+WALK_FRAME_7
	dw weskerbarry_left_spritesheet+WALK_FRAME_8

weskerbarry_front_left_walk_anim_pointers:
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_1
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_2
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_3
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_4
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_5
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_6
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_7
	dw weskerbarry_front_left_spritesheet+WALK_FRAME_8

;gun aim
weskerbarry_front_gun_aim_anim_pointers:
	dw weskerbarry_front_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_front_right_gun_aim_anim_pointers:
	dw weskerbarry_front_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_right_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_right_gun_aim_anim_pointers:
	dw weskerbarry_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_right_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_back_right_gun_aim_anim_pointers:
	dw weskerbarry_back_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_right_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_right_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_back_gun_aim_anim_pointers:
	dw weskerbarry_back_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_back_left_gun_aim_anim_pointers:
	dw weskerbarry_back_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_back_left_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_left_gun_aim_anim_pointers:
	dw weskerbarry_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_left_spritesheet+NPC_GUN_AIM_FRONT

weskerbarry_front_left_gun_aim_anim_pointers:
	dw weskerbarry_front_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_left_spritesheet+NPC_GUN_AIM_FRONT
	dw weskerbarry_front_left_spritesheet+NPC_GUN_AIM_FRONT

;shotgun aim
weskerbarry_front_shotgun_aim_anim_pointers:
	dw weskerbarry_front_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_front_right_shotgun_aim_anim_pointers:
	dw weskerbarry_front_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_right_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_right_shotgun_aim_anim_pointers:
	dw weskerbarry_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_right_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_back_right_shotgun_aim_anim_pointers:
	dw weskerbarry_back_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_right_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_right_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_back_shotgun_aim_anim_pointers:
	dw weskerbarry_back_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_back_left_shotgun_aim_anim_pointers:
	dw weskerbarry_back_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_back_left_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_left_shotgun_aim_anim_pointers:
	dw weskerbarry_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_left_spritesheet+NPC_SHOTGUN_AIM_FRONT

weskerbarry_front_left_shotgun_aim_anim_pointers:
	dw weskerbarry_front_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_left_spritesheet+NPC_SHOTGUN_AIM_FRONT
	dw weskerbarry_front_left_spritesheet+NPC_SHOTGUN_AIM_FRONT

;checking
weskerbarry_front_checking_anim_pointers:
	dw weskerbarry_front_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_spritesheet+NPC_CHECKING_FRAME

weskerbarry_front_right_checking_anim_pointers:
	dw weskerbarry_front_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_right_spritesheet+NPC_CHECKING_FRAME

weskerbarry_right_checking_anim_pointers:
	dw weskerbarry_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_right_spritesheet+NPC_CHECKING_FRAME

weskerbarry_back_right_checking_anim_pointers:
	dw weskerbarry_back_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_right_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_right_spritesheet+NPC_CHECKING_FRAME

weskerbarry_back_checking_anim_pointers:
	dw weskerbarry_back_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_spritesheet+NPC_CHECKING_FRAME

weskerbarry_back_left_checking_anim_pointers:
	dw weskerbarry_back_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_back_left_spritesheet+NPC_CHECKING_FRAME

weskerbarry_left_checking_anim_pointers:
	dw weskerbarry_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_left_spritesheet+NPC_CHECKING_FRAME

weskerbarry_front_left_checking_anim_pointers:
	dw weskerbarry_front_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_left_spritesheet+NPC_CHECKING_FRAME
	dw weskerbarry_front_left_spritesheet+NPC_CHECKING_FRAME
