text_3E4000: ;F9:4000
	text		"My dear Alma"
	newLine		""
	newLine		"The fact that you"
	newLine		"have received this"
	newLine		"letter is both a joy"
	newLine		"and a sadness for"
	newLine		"me."
	newLine		"I could not even"
	newLine		"talk to you because"
	newLine		"of that guy in the"
	newLine		"sunglasses."
	newLine		"Alma, be calm and"
	newLine		"read this."
	nextPage	"I think I've told"
	newLine		"you that I moved to"
	newLine		"a pharmaceutical"
	newLine		"company's lab."
	newLine		"They headhunted me."
	newLine		"Last month, there"
	newLine		"was an accident in"
	newLine		"the lab, and the"
	newLine		"virus we were"
	newLine		"studying escaped."
	nextPage	"All my colleagues"
	newLine		"who were infected"
	newLine		"by the virus are"
	newLine		"dead."
	newLine		"To be accurate,"
	newLine		"they're not dead."
	newLine		"They still wander"
	newLine		"around."
	newLine		"Actually, some of"
	newLine		"them are knocking"
	newLine		"on my room door"
	newLine		"desperately right"
	newLine		"now."
	newLine		"But there's no"
	newLine		"sign of"
	newLine		"intelligence in"
	newLine		"their eyes."
	nextPage	"That cursed virus"
	newLine		"takes away all"
	newLine		"humanity from the"
	newLine		"human brain."
	newLine		"Love, joy, sorrow,"
	newLine		"fear, humor..."
	newLine		"eternally."
	newLine		""
	newLine		"And Alma, even the"
	newLine		"memories of the days"
	newLine		"I spent with you..."
	newLine		""
	newLine		"Yes, I'm infected."
	newLine		"I did everything I"
	newLine		"could, but I could"
	newLine		"only delay the"
	newLine		"progress by a few"
	newLine		"days."
	nextPage	"The most"
	newLine		"frightening thing"
	newLine		"is that I have"
	newLine		"begun to forget"
	newLine		"about you day by"
	newLine		"day."
	newLine		""
	newLine		"So I chose a"
	newLine		"peaceful death,"
	newLine		"rather than"
	newLine		"becoming the"
	newLine		"living dead."
	nextPage	"Within an hour,"
	newLine		"I will have"
	newLine		"entered my"
	newLine		"eternal sleep."
	newLine		"I do hope you'll"
	newLine		"understand my"
	newLine		"decision..."
	newLine		"Good Bye and"
	newLine		"Forever Yours,"
	newLine		""
	newLine		"Martin Crackhorn"
	eof

text_3E4498: ;F9:4498
	text		"May 9, 1998"
	newLine		""
	newLine		"At night, we played"
	newLine		"Poker with Scott"
	newLine		"the guard, Alias and"
	newLine		"Steve the"
	newLine		"researcher."
	newLine		"Steve was really"
	newLine		"lucky, but I think"
	newLine		"he was cheating."
	newLine		"What a scumbag."
	eof

text_3E453B: ;F9:453B
	text		"May 10, 1998"
	newLine		""
	newLine		"Today, a high"
	newLine		"ranking researcher"
	newLine		"asked me to take"
	newLine		"care of a new"
	newLine		"monster. It looks"
	newLine		"like a gorilla"
	newLine		"without any skin."
	nextPage	"They told me to"
	newLine		"feed them live"
	newLine		"food."
	newLine		"When I threw in a"
	newLine		"pig, they were"
	newLine		"playing with it..."
	newLine		"tearing off the"
	newLine		"pig's legs and"
	newLine		"pulling out the"
	newLine		"guts before they"
	newLine		"actually ate it."
	eof

text_3E4668: ;F9:4668
	text		"May 11, 1998"
	newLine		""
	newLine		"Around 5 o'clock"
	newLine		"this morning,"
	newLine		"Scott came in and"
	newLine		"woke me up"
	newLine		"suddenly. He was"
	newLine		"wearing a"
	newLine		"protection suit"
	newLine		"that looks like a"
	newLine		"space suit."
	nextPage	"He told"
	newLine		"me to put one as"
	newLine		"well. I heard there"
	newLine		"was an accident in"
	newLine		"the lab in the"
	newLine		"basement. It's no"
	newLine		"wonder, those"
	newLine		"researchers never"
	newLine		"rest, even at night."
	eof

text_3E4793: ;F9:4793
	text		"May 12, 1998"
	newLine		""
	newLine		"I've been wearing"
	newLine		"this annoying space"
	newLine		"suit since"
	newLine		"yesterday, my skin"
	newLine		"grows musty and"
	newLine		"feels very itchy."
	newLine		"By way of revenge,"
	newLine		"I didn't feed those"
	newLine		"dogs today. Now I"
	newLine		"feel better."
	eof

text_3E484E: ;F9:484E
	text		"May 13, 1998"
	newLine		""
	newLine		"I went to the"
	newLine		"medical room"
	newLine		"because my back is"
	newLine		"all swollen and"
	newLine		"feels itchy. They"
	newLine		"put a big bandage"
	newLine		"on my back, and the"
	newLine		"doctor told me I"
	newLine		"did not need to"
	newLine		"wear the space suit"
	newLine		"any more. I guess I"
	newLine		"can sleep well"
	newLine		"tonight."
	db $00 ;%fix eof

text_3E4933: ;F9:4933
	text		"May 14, 1998"
	newLine		""
	newLine		"When I woke up this"
	newLine		"morning, I found"
	newLine		"another blister on"
	newLine		"my foot. It was"
	newLine		"annoying, and I"
	newLine		"ended up dragging"
	newLine		"my foot as I went to"
	newLine		"the dogs' pen. They"
	newLine		"have been quiet"
	newLine		"since morning, which"
	newLine		"is very unusual."
	nextPage	"I found that some of"
	newLine		"them had escaped."
	newLine		"I'll be in real"
	newLine		"trouble if the"
	newLine		"higher-ups find out."
	eof

text_3E4A67: ;F9:4A67
	text		"May 15, 1998"
	newLine		""
	newLine		"Even though I didn't"
	newLine		"feel well, I decided"
	newLine		"to go to see Nancy."
	newLine		"It's my first day"
	newLine		"off in a long time."
	newLine		"But I was stopped by"
	newLine		"the guard on the way"
	newLine		"out. They say the"
	newLine		"company has ordered"
	newLine		"that no one leave"
	newLine		"the grounds. I can't"
	newLine		"even make a phone"
	newLine		"call. What kind of"
	newLine		"joke is this?!"
	db $00 ;%fix eof

text_3E4B84: ;4B84
	text		"May 16, 1998"
	newLine		""
	newLine		"I heard a researcher"
	newLine		"who tried to escape"
	newLine		"from this mansion"
	newLine		"was shot last night."
	newLine		"My entire body feels"
	newLine		"burning and itchy at"
	newLine		"night. When I was"
	newLine		"scratching the"
	newLine		"swelling on my arm,"
	newLine		"a lump of rotten"
	newLine		"flesh dropped off."
	newLine		"What the hell is"
	newLine		"happening to me?"
	eof

text_3E4C88: ;F9:4C88
	text		"May 19, 1998"
	newLine		""
	newLine		"Fever go but itchy."
	newLine		"Hungry and eat"
	newLine		"doggie food. Itchy"
	newLine		"itchy Scott came."
	newLine		"Ugly face so"
	newLine		"killed him."
	newLine		"Tasty."
	eof

text_3E4CFF: ;F9:4CFF
	text		"Itchy."
	newLine		"Tasty."
	eof

text_3E4D0E: ;F9:4D0E
	text		"4 days have passed"
	newLine		"since the accident,"
	newLine		"and the plant at"
	newLine		"Point 42 is growing"
	newLine		"amazingly fast."
	newLine		""
	newLine		"It has been effected"
	newLine		"by the T-Virus"
	newLine		"differently than"
	newLine		"other plants have"
	newLine		"been, and shows"
	newLine		"unique shape in"
	newLine		"addition to its"
	newLine		"size. Looking at the"
	newLine		"way it behaves, it"
	newLine		"is now difficult to"
	newLine		"determine what kind"
	newLine		"of plant it was"
	newLine		"originally."
	nextPage	"There are two ways"
	newLine		"in which Plant 42"
	newLine		"gathers nutrition."
	newLine		"The first one is"
	newLine		"through its root"
	newLine		"that reaches into"
	newLine		"the basement."
	newLine		"Immediately after"
	newLine		"the accident, a"
	newLine		"scientist went mad"
	newLine		"and broke the water"
	newLine		"tank in the"
	newLine		"basement. Now the"
	newLine		"basement is filled"
	newLine		"with water. It is"
	newLine		"easily imaginable"
	newLine		"that some chemical"
	newLine		"elements were"
	newLine		"blended in the"
	newLine		"water and promotes"
	newLine		"the incredibly fast"
	newLine		"growth of Plant 42."
	nextPage	"Another part of"
	newLine		"Plant 42 from the"
	newLine		"basement grows"
	newLine		"through the duct"
	newLine		"and hangs down like"
	newLine		"so many bulbs from"
	newLine		"the ceiling of"
	newLine		"first floor. Many"
	newLine		"vines come out of"
	newLine		"those bulbs, and"
	newLine		"they are the second"
	newLine		"resource for its"
	newLine		"nutrition."
	nextPage	"Once sensing"
	newLine		"movement, Plant 42"
	newLine		"shoots its vines"
	newLine		"around the prey,"
	newLine		"and holds it. Then"
	newLine		"it starts sucking"
	newLine		"up blood, using the"
	newLine		"suckers located at"
	newLine		"the back of its"
	newLine		"vine."
	newLine		""
	newLine		"It also has some"
	newLine		"intelligence, and"
	newLine		"blocks the door by"
	newLine		"twining its vine to"
	newLine		"it especially when"
	newLine		"it captures prey or"
	newLine		"is sleeping."
	nextPage	"Several staff"
	newLine		"members have already"
	newLine		"fallen victims to"
	newLine		"this."
	eof

text_3E5211: ;F9:5211
	text		"RACCOON TIMES"
	newLine		"MAY 27, 1998"
	newLine		""
	newLine		"ANIMAL ATTACK?"
	newLine		"WOMAN MUTILATED"
	newLine		""
	newLine		"May 20."
	newLine		"Around 10 PM"
	newLine		"a 20-year old young"
	newLine		"woman's body was"
	newLine		"found by a passer-by"
	newLine		"on the left bank of"
	newLine		"Marble River in"
	newLine		"Cider District of"
	newLine		"Raccoon City."
	nextPage	"Raccoon police"
	newLine		"assume it to be a"
	newLine		"grizzly or other"
	newLine		"animal's doing"
	newLine		"because there are"
	newLine		"teeth marks along"
	newLine		"her mutilated arms"
	newLine		"and left foot that"
	newLine		"show considerable"
	newLine		"power. Since she was"
	newLine		"wearing a hiking"
	newLine		"boot on her"
	newLine		"remaining foot, it"
	newLine		"has been determined"
	newLine		"that she was"
	newLine		"attacked in the"
	newLine		"Arklay mountains and"
	newLine		"fell to the river."
	newLine		"They are urrying to"
	newLine		"identify this woman."
	eof

text_3E5446: ;F9:5446
	text		"RACCOON WEEKLY"
	newLine		" JUNE 16, 1998"
	newLine		""
	newLine		"MONSTERS IN"
	newLine		"ARKLAY MOUNTAINS?"
	newLine		""
	newLine		"Some people claim"
	newLine		"they've seen"
	newLine		"monsters in the"
	newLine		"Arklay mountains."
	newLine		"The monsters are"
	newLine		"supposedly about"
	newLine		"the same size as"
	newLine		"large dogs and"
	newLine		"usually run in a"
	newLine		"pack as wolves do."
	nextPage	"This may sound like"
	newLine		"a group of ordinary"
	newLine		"wild dogs, but these"
	newLine		"monsters are"
	newLine		"surprisingly fierce"
	newLine		"and hard to hurt."
	newLine		"They say these dogs"
	newLine		"won't bother you"
	newLine		"unless you wake"
	newLine		"them, so you smart"
	newLine		"readers should stay"
	newLine		"out of the Arklay"
	newLine		"Mountains for the"
	newLine		"time being. But if"
	newLine		"you're looking for"
	newLine		"adventure, check it"
	newLine		"out! You wanna try?"
	eof

text_3E566B: ;F9:566B
	text		"RACCOON TIMES"
	newLine		"JULY 9, 1998"
	newLine		""
	newLine		"MYSTERY ON"
	newLine		"ARKLAY MOUNTAINS!"
	newLine		"MOUNTAIN ROAD"
	newLine		"BLOCKED"
	newLine		""
	newLine		"Due to successive"
	newLine		"disasters in the"
	newLine		"Arklay Mountains,"
	newLine		"the city authorities"
	newLine		"have decided to"
	newLine		"block the road"
	newLine		"leading to the"
	newLine		"foothills."
	db $02,		"At the" ;%fix
	newLine		"same time, Raccoon"
	newLine		"police intend to"
	newLine		"begin the search for"
	newLine		"lost people with the"
	newLine		"help of STARS team"
	newLine		"members. They expect"
	newLine		"great difficulty"
	newLine		"because of the vast"
	newLine		"size of Arklay"
	newLine		"Mountains and the"
	newLine		"primeval forest that"
	newLine		"covers most of the"
	newLine		"area. Also people"
	newLine		"are still reporting"
	newLine		"sightings of"
	newLine		"horrible monsters in"
	newLine		"the mountains."
	eof

text_3E5881: ;F9:5881
	text		"HELICOPTER PORT"
	newLine		""
	newLine		"Executives and"
	newLine		"Government Officials"
	newLine		"only on helicopter"
	newLine		"port."
	newLine		"This restriction may"
	newLine		"not apply in case of"
	newLine		"an accident."
	eof

text_3E5907: ;F9:5907
	text		"PASSAGE TO THE"
	newLine		"HELICOPTER"
	newLine		""
	newLine		"No one is allowed to"
	newLine		"enter unless they"
	newLine		"are attended by a"
	newLine		"Research Consultant"
	newLine		"or Security"
	newLine		"Director. All others"
	newLine		"will be shot on"
	newLine		"sight."
	eof

text_3E59A8: ;F9:59A8
	text		"ELEVATOR"
	newLine		""
	newLine		"The elevator stops"
	newLine		"during emergencies."
	eof

text_3E59DA: ;F9:59DA
	text		"VIDEO DATA ROOM"
	newLine		""
	newLine		"Video Data Room is"
	newLine		"within the control"
	newLine		"of Special Research"
	newLine		"Division. Keith"
	newLine		"Arving, the Room"
	newLine		"Manager, is"
	newLine		"designated to have"
	newLine		"jurisdiction over"
	newLine		"room usage."
	eof

text_3E5A84: ;F9:5A84
	text		"PRISON"
	newLine		""
	newLine		"Sanitation Division"
	newLine		"controls the usage"
	newLine		"of the prison."
	newLine		"Consultant"
	newLine		"Researchers"
	newLine		"(E. Smith, S. Ross,"
	newLine		"A. Wesker) must be"
	newLine		"present if virus"
	newLine		"is used."
	eof

text_3E5B1B: ;F9:5B1B
	text		"TRIPLE LOCK DOOR"
	newLine		""
	newLine		"No one is allowed"
	newLine		"to enter unless he"
	newLine		"presents all pass"
	newLine		"code documents."
	newLine		"Pass code documents"
	newLine		"must be created on"
	newLine		"the specialized"
	newLine		"output machine by"
	newLine		"the Chief"
	newLine		"Researcher of each"
	newLine		"block."
	eof

text_3E5BE2: ;F9:5BE2
	text		"POWER ROOM"
	newLine		""
	newLine		"Only Headquarters"
	newLine		"Supervisors may"
	newLine		"enter. This"
	newLine		"restriction may not"
	newLine		"apply if the"
	newLine		"Consultant"
	newLine		"Researcher has"
	newLine		"received special"
	newLine		"instructions."
	eof

text_3E5C77: ;F9:5C77
	text		"PASS CODE OUTPUT"
	newLine		"MACHINE"
	newLine		""
	newLine		"No one is allowed"
	newLine		"to use the pass code"
	newLine		"output machine but"
	newLine		"the Chief"
	newLine		"Researchers."
	eof

text_3E5CE3: ;F9:5CE3
	text		"TOP SECRET"
	newLine		""
	newLine		"Regarding the"
	newLine		"progress of 'Tyrant'"
	newLine		"after the use of"
	newLine		"t-virus..."
	eof

text_3E5D2F: ;F9:5D2F
	text		"June 8, 1998"
	newLine		""
	newLine		"Dear Ada,"
	newLine		""
	newLine		"Ada, by the time you"
	newLine		"read this, I'll be"
	newLine		"something..."
	newLine		"different. Today's"
	newLine		"test turned out to"
	newLine		"be positive, just as"
	newLine		"I expected. I feel"
	newLine		"like going crazy"
	newLine		"when I think about"
	newLine		"becoming one of"
	newLine		"them."
	nextPage	"Ada, you're not"
	newLine		"infected, and I hope"
	newLine		"you never will be."
	newLine		"In case you're the"
	newLine		"last one left, take"
	newLine		"the material in the"
	newLine		"Meeting Room and go"
	newLine		"to the Power Room to"
	newLine		"operate the"
	newLine		"Triggering System"
	newLine		"before you escape."
	newLine		"And make all this"
	newLine		"public through the"
	newLine		"media."
	nextPage	"If everything is in"
	newLine		"order, all the locks"
	newLine		"can be opened by the"
	newLine		"security system. You"
	newLine		"can access to the"
	newLine		"security system from"
	newLine		"the terminal in the"
	newLine		"small laboratory"
	newLine		"using my name. The"
	newLine		"password is your"
	newLine		"name. You'll need"
	newLine		"another password to"
	newLine		"unlock the door at"
	newLine		"B3 where the Meeting"
	newLine		"Room is located."
	nextPage	"Just in case you"
	newLine		"don't know, I've"
	newLine		"written the code"
	newLine		"below. I'm sure"
	newLine		"you'll understand"
	newLine		"it easily."
	newLine		""
	newLine		"And this is my last"
	newLine		"hope - if you find"
	newLine		"me completely"
	newLine		"changed, please"
	newLine		"kill me yourself."
	newLine		" "
	newLine		"PASSWORD="
	newLine		" "
	newLine		"John Clemens"
	eof

text_3E60F7: ;F9:60F7
	text		"1/3"
	newLine		""
	newLine		"As I stated in the"
	newLine		"last report, there"
	newLine		"are some common"
	newLine		"features found in"
	newLine		"the cells of the"
	newLine		"plant infected by"
	newLine		"Tyrant virus. We"
	newLine		"also have found"
	newLine		"another interesting"
	newLine		"fact through some"
	newLine		"experiments."
	nextPage	"We found an element"
	newLine		"that destroys these"
	newLine		"plant cells rapidly"
	newLine		"in 'UNB No.16', one"
	newLine		"of	the series of"
	newLine		"UNB chemicals that"
	newLine		"we used for that"
	newLine		"experiment. We named"
	newLine		"this 'UNB No.16' as"
	newLine		"'V-JOLT'. In our"
	newLine		"calculation, it will"
	newLine		"take less than 5"
	newLine		"seconds to destroy"
	newLine		"Plant 42 if we put"
	newLine		"the 'V-JOLT'"
	newLine		"directly on the"
	newLine		"root."
	eof

text_3E62EB: ;F9:62EB
	text		"2/3"
	newLine		""
	newLine		"'V-JOLT' must be"
	newLine		"created just before"
	newLine		"the usage, as it can"
	newLine		"not be kept for a"
	newLine		"long time. You need"
	newLine		"to mix some of the"
	newLine		"UNB series chemicals"
	newLine		"in a specific order"
	newLine		"to create 'V-JOLT'."
	newLine		"But the UNB series"
	newLine		"chemicals may"
	newLine		"generate a poisonous"
	newLine		"gas which is harmful"
	newLine		"to the human body."
	nextPage	"Extreme caution"
	newLine		"should be taken when"
	newLine		"handling these"
	newLine		"chemicals."
	newLine		""
	newLine		"First, following are"
	newLine		"the types of UNB"
	newLine		"series chemicals and"
	newLine		"their brief"
	newLine		"characteristics."
	nextPage	"UNB No.2  Red"
	newLine		"NP-003",$09,"Purple" ;%fix
	newLine		"UNB No.4 Green"
	newLine		"Yellow-6 Yellow"
	newLine		"UNB No.7  White"
	newLine		"UNB No.13 Blue"
	newLine		"(stimulating smell)"
	newLine		"V-JOLT (UNB No.16)"
	newLine		"Brown"
	newLine		""
	newLine		"*Mixing process"
	newLine		"starts from next"
	newLine		"page."
	eof

text_3E6548: ;F9:6548
	text		"-Genesis-"
	newLine		"'I swear by myself',"
	newLine		"declares the Lord,"
	newLine		"'that because you"
	newLine		"have done this and"
	newLine		"have not withheld"
	newLine		"your son, your only"
	newLine		"son, I will surely"
	newLine		"bless you and make"
	newLine		"your descendants as"
	newLine		"numerous as the"
	newLine		"stars in the sky,"
	newLine		"and as the sand on"
	newLine		"the seashore."
	nextPage	"Your descendants"
	newLine		"will take"
	newLine		"possession of the"
	newLine		"cities of their"
	newLine		"enemies, and through"
	newLine		"your offspring all"
	newLine		"nations on earth"
	newLine		"will be blessed,"
	newLine		"because you have"
	newLine		"obeyed me."
	newLine		""
	newLine		"(Genesis 22:"
	newLine		"16-17-18)"
	eof

text_3E66FF: ;F9:66FF
	text		"-About Medicinal"
	newLine		"Herbs-"
	newLine		""
	newLine		"As you may know,"
	newLine		"there are many"
	newLine		"plants that have"
	newLine		"medical effects."
	newLine		"Since ancient times,"
	newLine		"humans have been"
	newLine		"healing wounds and"
	newLine		"diseases using"
	newLine		"various plants."
	nextPage	"In this book, we're"
	newLine		"going to sample"
	newLine		"three herbs that"
	newLine		"grow around the"
	newLine		"Raccoon mountains,"
	newLine		"and give their"
	newLine		"outlines as examples"
	newLine		"of those plants with"
	newLine		"medical properties."
	nextPage	"Each herb has"
	newLine		"different colors and"
	newLine		"different effects as"
	newLine		"medical plants: the"
	newLine		"green one recovers"
	newLine		"physical strength,"
	newLine		"the blue one"
	newLine		"neutralizes natural"
	newLine		"toxins, while the"
	newLine		"red herb does not"
	newLine		"have any effect by"
	newLine		"itself."
	nextPage	"The red herb is only"
	newLine		"effective when it is"
	newLine		"mixed with other"
	newLine		"herbs. For example,"
	newLine		"if you mix this herb"
	newLine		"with the herb that"
	newLine		"recovers physical"
	newLine		"strength, the"
	newLine		"recovery effect will"
	newLine		"be doubled."
	nextPage	"By adjusting the"
	newLine		"amount and"
	newLine		"experimenting with"
	newLine		"these three herbs,"
	newLine		"you can create"
	newLine		"various kinds of"
	newLine		"medicines but I'll"
	newLine		"leave the details in"
	newLine		"your hands, because"
	newLine		"that's the best way"
	newLine		"to acquire true"
	newLine		"knowledge."
	eof

text_3E6AB3: ;F9:6AB3
	text		"F.B.I. Forcibly"
	newLine		"Investigates"
	newLine		"Umbrella Inc."
	eof

text_3E6ADF: ;F9:6ADF
	text		"Chairman Of Umbrella"
	newLine		"Inc. Taken Into"
	newLine		"Custody -First steps"
	newLine		"taken to disclose"
	newLine		"truth behind"
	newLine		"abnormal murder"
	newLine		"cases in Raccoon"
	newLine		"City-"
	eof

text_3E6B60: ;F9:6B60
	text		"Umbrella's Plot"
	newLine		"Exposed -Government"
	newLine		"denies knowledge-"
	eof

text_3E6B97: ;F9:6B97
	text		"Tyrant Virus"
	newLine		"Leakage Case Being"
	newLine		"Brought To Light"
	eof

text_3E6BC9: ;F9:6BC9
	text		"Abnormal Murders"
	newLine		"Solved -Umbrella"
	newLine		"executives admit"
	newLine		"their involvement-"
	eof

text_3E6C10: ;F9:6C10
	text		"Umbrella's Plot"
	newLine		"Foiled"
	eof

text_3E6C28: ;F9:6C28
	text		"Umbrella's Secret"
	newLine		"Agenda Unveiled"
	eof

text_3E6C4B: ;F9:6C4B
	text		"S.T.A.R.S. Units"
	newLine		"Have Been"
	newLine		"Established All"
	newLine		"Over The States"
	eof

text_3E6C87: ;F9:6C87
	text		"Umbrella's Special"
	newLine		"Virus Leakage Case"
	newLine		"-Was it an attempt"
	newLine		"to enter the"
	newLine		"weapons business?-"
	eof

text_3E6CE1: ;F9:6CE1
	text		"Umbrella's Virus"
	newLine		"Leakage Revealed"
	eof

;F9;6D04
